name: Test Python Partiels

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout your Python repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip wget

    - name: Download and extract Partiels binary
      run: |
        wget https://github.com/Ircam-Partiels/Partiels/releases/download/2.0.10/Partiels-Linux.tar.gz
        mkdir -p Partiels
        tar -xzf Partiels-Linux.tar.gz -C Partiels
        Partiels/Partiels/Partiels --help

    - name: Download and install Ircam Vamp Plugins
      run: |
        wget https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/Ircam-Vamp-Plugins-Linux.zip
        mkdir -p temp/Ircam-Vamp-Plugins-Linux
        unzip Ircam-Vamp-Plugins-Linux.zip -d temp/Ircam-Vamp-Plugins-Linux
        sh temp/Ircam-Vamp-Plugins-Linux/install.sh
        
        £wget https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/VAX-Vamp-Plugin-v1.0.0-Linux.zip
        £unzip VAX-Vamp-Plugin-v1.0.0-Linux.zip -d /opt/Partiels/PlugIns
        £wget https://github.com/Ircam-Partiels/crepe-vamp-plugin/releases/download/3.0.0/Crepe-Linux.tar.gz
        £tar -xzf Crepe-Linux.tar.gz -C /opt/Partiels/PlugIns
        £wget https://github.com/Ircam-Partiels/whisper-vamp-plugin/releases/download/3.0.0/Whisper-Linux.tar.gz
        £tar -xzf Whisper-Linux.tar.gz -C /opt/Partiels/PlugIns

    - name: list installed Ircam Vamp Plugins
      run: |
        ls /opt/Partiels/PlugIns

    - name: Set Partiels executable path dynamically
      run: |
        echo "PARTIELS_EXECUTABLE=$(realpath Partiels/Partiels/Partiels)" >> $GITHUB_ENV
        echo "VAMP_PATH=/opt/Partiels/PlugIns" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        pip install build pytest

    - name: Build python-partiels
      run: |
        python -m build
    
    - name: Install python-partiels
      run: |
        pip install dist/*.whl

    - name: Run tests
      run: |
        pytest tests/
