name: Build and Test Python Partiels (macOS)

on: [push, pull_request]

jobs:
  build-test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Etapes spécifiques à macOS
      - name: Install system dependencies (macOS)
        run: |
          brew install wget unzip

      - name: Download and install Partiels (macOS)
        run: |
          wget https://github.com/Ircam-Partiels/Partiels/releases/download/2.0.10/Partiels-MacOS.dmg
          hdiutil attach Partiels-MacOS.dmg
          sudo cp -R /Volumes/Partiels/Partiels.app /Applications/
          hdiutil detach /Volumes/Partiels

      - name: Install Ircam Vamp Plugins (macOS)
        run: |
          wget https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/Ircam-Vamp-Plugins-MacOS.zip
          wget https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/VAX-Vamp-Plugin-v1.0.0-MacOS.zip
          wget https://github.com/Ircam-Partiels/crepe-vamp-plugin/releases/download/3.0.0/Crepe-MacOS.pkg
          wget https://github.com/Ircam-Partiels/whisper-vamp-plugin/releases/download/3.0.0/Whisper-MacOS.pkg

      - name: Install Ircam Vamp Plugins (macOS) - Extraction and Installation
        run: |
          mkdir $HOME/vamp
          unzip Ircam-Vamp-Plugins-MacOS.zip
          cp Ircam-Vamp-Plugins-MacOS/*.dylib $HOME/vamp
          unzip VAX-Vamp-Plugin-v1.0.0-MacOS.zip $HOME/vamp
          cp VAX-Vamp-Plugin/*.dylib /usr/local/lib/ $HOME/vamp
          sudo installer -pkg Crepe-MacOS.pkg -target $HOME/vamp
          sudo installer -pkg Whisper-MacOS.pkg -target $HOME/vamp

      - name: Install Python dependencies
        run: |
          pip install build pytest

      - name: Build python-partiels
        run: |
          python -m build

      - name: Install python-partiels
        run: |
          pip install dist/*.whl

      - name: Run tests
        run: |
          pytest tests/
