name: Test Python Partiels Windows

on: [push, pull_request]

jobs:
  build-test:
    runs-on: windows-2022

    steps:
    - name: Checkout your Python repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        choco install wget unzip
      shell: powershell

    - name: Download and extract Partiels binary
      run: |
        wget https://github.com/Ircam-Partiels/Partiels/releases/download/2.0.10/Partiels-Windows.zip
        unzip Partiels-Windows.zip -d Partiels
        Partiels\Partiels.exe --help
      shell: powershell

    - name: Download Ircam Vamp Plugins
      run: |
        wget https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/Ircam-Vamp-Plugins-Windows.zip
        wget https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/VAX-Vamp-Plugin-v1.0.0-Windows.zip
        wget https://github.com/Ircam-Partiels/crepe-vamp-plugin/releases/download/3.0.0/Crepe-Windows.zip
        wget https://github.com/Ircam-Partiels/whisper-vamp-plugin/releases/download/3.0.0/Whisper-Windows.zip
      shell: powershell

    - name: Install Ircam Vamp Plugins
      run: |
        mkdir $env:USERPROFILE\vamp
        unzip Ircam-Vamp-Plugins-Windows.zip -d Ircam-Vamp-Plugins
        Copy-Item Ircam-Vamp-Plugins\*.dll $env:USERPROFILE\vamp\
        unzip VAX-Vamp-Plugin-v1.0.0-Windows.zip -d VAX-Vamp-Plugin
        Copy-Item VAX-Vamp-Plugin\*.dll $env:USERPROFILE\vamp\
        unzip Crepe-Windows.zip -d Crepe
        Copy-Item Crepe\*.dll $env:USERPROFILE\vamp\
        unzip Whisper-Windows.zip -d Whisper
        Copy-Item Whisper\*.dll $env:USERPROFILE\vamp\
      shell: powershell

    - name: List installed Ircam Vamp Plugins
      run: |
        Get-ChildItem $env:USERPROFILE\vamp
      shell: powershell

    - name: Install Python dependencies
      run: |
        pip install build pytest
      shell: powershell

    - name: Build python-partiels
      run: |
        python -m build
      shell: powershell
    
    - name: Install python-partiels
      run: |
        pip install dist\*.whl
      shell: powershell

    - name: Run tests
      run: |
        pytest tests/
      shell: powershell
