name: Test Python Partiels

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout your Python repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip wget

    - name: Download and extract Partiels binary
      run: |
        wget https://github.com/Ircam-Partiels/Partiels/releases/download/2.0.10/Partiels-Linux.tar.gz
        mkdir -p Partiels
        tar -xzf Partiels-Linux.tar.gz -C Partiels

    - name: Download and install Ircam Vamp Plugins
      run: |
        mkdir -p /opt/Partiels/PlugIns
        wget https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/Ircam-Vamp-Plugins-Linux.zip
        unzip Ircam-Vamp-Plugins-Linux.zip -d /opt/Partiels/PlugIns

    - name: Make Partiels executable
      run: |
        chmod +x Partiels/Partiels

    - name: Set Partiels executable path dynamically
      run: |
        echo "PARTIELS_EXECUTABLE=$(realpath Partiels/Partiels)" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        pip install build pytest

    - name: Build python-partiels
      run: |
        python -m build
    
    - name: Install python-partiels
      run: |
        pip install dist/*.whl

    - name: Run tests
      env:
        PARTIELS_EXECUTABLE: ${{ env.PARTIELS_EXECUTABLE }}
      run: |
        pytest tests/
