name: Build and Test Python Partiels (Common Steps)

on: [push, pull_request]

jobs:
  build-test-common:
    steps:
    - name: Install Python dependencies
      run: |
        pip install build pytest

    - name: Build python-partiels
      run: |
        python -m build
    
    - name: Install python-partiels
      run: |
        pip install dist/*.whl

    - name: Run tests
      run: |
        pytest tests/