name: Test Python Partiels

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout your Python repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip wget

    - name: Download and extract Partiels binary
      run: |
        wget https://github.com/Ircam-Partiels/Partiels/releases/download/2.0.10/Partiels-Linux.tar.gz
        tar -xzf Partiels-Linux.tar.gz
        sh Partiels/Partiels-install.sh
        Partiels/Partiels --help

    - name: Download Ircam Vamp Plugins
      run: |
        wget https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/Ircam-Vamp-Plugins-Linux.zip
        wget https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/VAX-Vamp-Plugin-v1.0.0-Linux.zip
        wget https://github.com/Ircam-Partiels/crepe-vamp-plugin/releases/download/3.0.0/Crepe-Linux.tar.gz
        wget https://github.com/Ircam-Partiels/whisper-vamp-plugin/releases/download/3.0.0/Whisper-Linux.tar.gz
   
    - name: Install Ircam Vamp Plugins
      run: |
        mkdir $HOME/vamp
        unzip Ircam-Vamp-Plugins-Linux.zip
        cp Ircam-Vamp-Plugins-Linux/*.so $HOME/vamp/
        unzip VAX-Vamp-Plugin-v1.0.0-Linux.zip
        tar -xzf VAX-Vamp-Plugin-Linux.tar.gz
        cp VAX-Vamp-Plugin/*.so $HOME/vamp/
        tar -xzf Crepe-Linux.tar.gz
        cp Crepe/*.so $HOME/vamp/
        tar -xzf Whisper-Linux.tar.gz
        cp Whisper/*.so $HOME/vamp/

    - name: list installed Ircam Vamp Plugins
      run: |
        ls $HOME/vamp

    #- name: Set Partiels executable path dynamically
    #  run: |
    #    echo "PARTIELS_EXECUTABLE=$(realpath Partiels/Partiels)" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        pip install build pytest

    - name: Build python-partiels
      run: |
        python -m build
    
    - name: Install python-partiels
      run: |
        pip install dist/*.whl

    - name: Run tests
      run: |
        pytest tests/
